from fastapi import Request

from src.common.logging import logger


async def logging_middleware(request: Request, call_next_handler):
    """
    Structured logging middleware for monitoring API request lifecycles.

    Args:
        request (Request): The incoming FastAPI request.
        call_next_handler: The next function in the middleware chain.

    Returns:
        Response: The API response generated by the application.
    """
    logger.info(
        "Processing API request",
        method=request.method,
        path=str(request.url.path)
    )

    api_response = await call_next_handler(request)

    logger.info(
        "API request finalized",
        status_code=api_response.status_code
    )

    return api_response
